### PR TITLE
Add info about arch aur package

### PR DESCRIPTION
**Pull request by dasJ**

### CODE REVIEW

**Comment by kennylevinsen** [comment]
Thanks for making the package!

**Comment by dasJ** [comment]
This Software is worth it ;)

2015-09-03 13:43 GMT+02:00 Kenny Levinsen notifications@github.com:

**Comment by kennylevinsen** [comment]
Oh, stop it you!

**Comment by dasJ** [comment]
No, I'm serious. It is relly useful. Strange nobody else had this idea years ago

**Comment by kennylevinsen** [comment]
Some had, but with different things in mind. After making this myself, I found a few solutions to specifically have SSH and HTTP together, for example, and a few that also could detect TLS. None had the concept of transports though, and most lacked more generic configurability.

But it's nice to get some feedback. All I know about the project is that the Starred counter keeps increasing, but I have no clue if that actually means that it is being used, or just +1'd. :confused:

**Comment by dasJ** [comment]
I mainly use it to get past some firewalls (blocking everything except port 20, 80, and 443). I have both my nginx and my sshd on port 80 using serve2d. It was pretty straight forward using your example configuration.

awesome_smiley___whaaplz_bigger_version_by_lasalle1alpha-d5c89m6

EDIT: Having this conversation shows how bored I am :joy:

**Pull request merged**
